name: Auto Merge main to gh-pages

on:
  push:
    branches:
      - main

jobs:
  merge-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTION_PUSH_TOKEN }}

      - name: Merge main into gh-pages
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git checkout gh-pages
          git merge --no-ff --no-edit main

      - name: Install Image Optimization Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick optipng

      - name: Run Image Processing Script
        run: |
          chmod +x process_images.sh
          ./process_images.sh

      - name: Commit Processed Images
        run: |
          # Only commit if there are changes (avoids empty commit error)
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Process images via GitHub Action"
            git push origin gh-pages
          fi